-- Add figure_svg column to questions table
ALTER TABLE questions ADD COLUMN IF NOT EXISTS figure_svg TEXT;

-- Add comment
COMMENT ON COLUMN questions.figure_svg IS 'SVG code for figures/diagrams generated by AI';
